// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/Application/AppProvider.vue')['default']
    DarkSwitch: typeof import('./src/components/Application/DarkSwitch.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IMaterialSymbolsBedtimeOutline: typeof import('~icons/material-symbols/bedtime-outline')['default']
    IMaterialSymbolsFullscreenExitRounded: typeof import('~icons/material-symbols/fullscreen-exit-rounded')['default']
    IMaterialSymbolsFullscreenRounded: typeof import('~icons/material-symbols/fullscreen-rounded')['default']
    IMaterialSymbolsSunny: typeof import('~icons/material-symbols/sunny')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
